server:
  port: 9100

spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: {amazing-hub-382703-3227eac99a82.json}
        project-id: {amazing-hub-382703}
        bucket: kookbee-test-strorage
  datasource:
    url: jdbc:mysql://10.178.0.3:3306/kookbee_bootcamp?serverTimezone=Asia/Seoul
    username: bee
    password: 1q2w3e4r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: 35.205.7.177
      port: 6379
  application:
    name: class-service
  servlet:
    multipart:
      max-file-size: 1000MB
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.64.69.238:8761/eureka
#      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


